HW_models: NRF_RTC: Fix compare event missed when interrupt disabled
BabbleSim/ext_NRF52_hw_models pull request #17
Opened 2020-12-09 11:28 UTC by nordic-krch

If compare event interrupt was disabled and event occurred then
that interrupt was not triggered after interrupt re-enabling.

Added storing that information in the event handler and then
when interrupt is reenabled this information is used to determine
if interrupt shall be triggered.

Signed-off-by: Krzysztof Chruscinski <krzysztof.chruscinski@nordicsemi.no>

2020-12-09 14:23 UTC, aescolar commented on src/HW_models/NRF_RTC.c
> +void nrf_rtc_regw_sideeffect_TASKS_START(int i) { NRF_RTC_Type *RTC_regs = &NRF_RTC_regs[i];
typo?

2020-12-09 14:32 UTC, nordic-krch commented on src/HW_models/NRF_RTC.c
> +void nrf_rtc_regw_sideeffect_TASKS_START(int i) { NRF_RTC_Type *RTC_regs = &NRF_RTC_regs[i];
right, fixed.

2020-12-09 14:32 UTC, nordic-krch commented
Zephyr PR: https://github.com/zephyrproject-rtos/zephyr/pull/30487
Just turned green.

2020-12-09 14:37 UTC, aescolar commented on src/HW_models/NRF_RTC.c
> +void nrf_rtc_regw_sideeffect_TASKS_START(int i) { NRF_RTC_Type *RTC_regs = &NRF_RTC_regs[i];
not a good fix :p

2020-12-09 14:51 UTC, aescolar requested changes
Yep, seems there was a bug here (according to the infocenter drawigns :) ). So overall the fix should go in. Just some minor things:

```diff
diff --git a/src/HW_models/NRF_RTC.c b/src/HW_models/NRF_RTC.c
index 325b3db..5c94e53 100644
--- a/src/HW_models/NRF_RTC.c
+++ b/src/HW_models/NRF_RTC.c
@@ -212,7 +212,6 @@ static ppi_event_types_t get_event(int rtc)
       break;
     case 2:
       event = RTC2_EVENTS_COMPARE_0;
-      bs_trace_error_line_time("There is no IRQ mapped for RTC2\n");
       break;
     }
 
@@ -225,7 +224,6 @@ void nrf_rtc_timer_triggered() {
       continue;
     }
     ppi_event_types_t event = get_event(rtc);
-    unsigned int irq_t      = get_irq_t(rtc);
 
     NRF_RTC_Type *RTC_regs = &NRF_RTC_regs[rtc];
 
@@ -243,7 +241,7 @@ void nrf_rtc_timer_triggered() {
             nrf_ppi_event(event);
           }
           if ( RTC_INTEN[rtc] & mask ){
-            hw_irq_ctrl_set_irq(irq_t);
+            hw_irq_ctrl_set_irq(get_irq_t(rtc));
           }
         }
       } //if cc_timers[rtc][cc] == Timer_RTC
@@ -330,6 +328,7 @@ void nrf_rtc2_TASKS_STOP()  { nrf_rtc_TASKS_STOP(2);  }
 void nrf_rtc2_TASKS_CLEAR() { nrf_rtc_TASKS_CLEAR(2); }
 
 void nrf_rtc_regw_sideeffect_TASKS_START(int i) {
+  NRF_RTC_Type *RTC_regs = &NRF_RTC_regs[i];
   if ( RTC_regs->TASKS_START ){
     RTC_regs->TASKS_START = 0;
     nrf_rtc_TASKS_START(i);
@@ -355,14 +354,14 @@ void nrf_rtc_regw_sideeffect_TASKS_CLEAR(int i) {
 void nrf_rtc_regw_sideeffect_INTENSET(int i) {
   NRF_RTC_Type *RTC_regs = &NRF_RTC_regs[i];
   if ( RTC_regs->INTENSET ){
-    uint32_t intenset = RTC_regs->INTENSET;
+    uint32_t new_interrupts = RTC_regs->INTENSET & ~RTC_INTEN[i];
     unsigned int irq_t = get_irq_t(i);
     uint32_t mask = RTC_EVTEN_COMPARE0_Msk;
 
     RTC_INTEN[i] |= RTC_regs->INTENSET;
     RTC_regs->INTENSET = RTC_INTEN[i];
     for ( int cc = 0 ; cc < N_CC ; cc++, mask <<=1) {
-      if (RTC_regs->EVENTS_COMPARE[cc] && (intenset & mask)) {
+      if (RTC_regs->EVENTS_COMPARE[cc] && (new_interrupts & mask)) {
         hw_irq_ctrl_set_irq(irq_t);
       }
     }

2020-12-09 14:51 UTC, aescolar commented on src/HW_models/NRF_RTC.c
>        bs_trace_error_line_time("There is no IRQ mapped for RTC2\n");
Not applicable for events

2020-12-09 14:51 UTC, aescolar commented on src/HW_models/NRF_RTC.c
> +    unsigned int irq_t      = get_irq_t(rtc);
I guess we can move this to the place where we use it, and in that way enable using the last RTC to generate PPI events

2020-12-09 14:51 UTC, aescolar commented on src/HW_models/NRF_RTC.c
> +    uint32_t intenset = RTC_regs->INTENSET;
Should this check only for the bits that were just enabled? (to avoid retriggering an interrupt if it was already set before?)

2020-12-10 06:46 UTC, nordic-krch commented
@aescolar thanks for review. Comments applied.

2020-12-10 10:58 UTC, aescolar approved these changes

2020-12-10 10:59 UTC, aescolar commented
@nordic-krch Can you please retrigger CI in zephyrproject-rtos/zephyr#30487

2020-12-10 11:01 UTC, nordic-krch commented
I did it this morning after applying fixes https://buildkite.com/zephyr/zephyr/builds/15467

2020-12-10 14:07 UTC, carlescufi commented
@aescolar is this ready for merging?

2020-12-10 14:14 UTC, wopu-ot approved these changes

2020-12-10 14:37 UTC, merged

2020-12-10 14:41 UTC, aescolar commented
> @aescolar is this ready for merging?

@carlescufi was just waiting for @wopu-ot review :)