fix unaligned access warnings
BabbleSim/ext_NRF52_hw_models pull request #23
Opened 2021-12-23 09:43 UTC by alxelax

No possible to build bsim tests with -Werror option.

Zephyr issue: https://github.com/zephyrproject-rtos/zephyr/issues/38303

There are potential unaligned access issues.
This PR fixes them.

Signed-off-by: Aleksandr Khromykh <aleksandr.khromykh@nordicsemi.no>

2021-12-23 14:44 UTC, aescolar commented
Note that the issue here seems to be gcc being extra zealous. Those accesses are halfwords properly halfword aligned (and this is x86 anyhow)

2021-12-23 14:45 UTC, aescolar commented
Would a -Wno-address-of-packed-member for this component cmake fix the issue?

2021-12-23 14:59 UTC, aescolar requested changes
> Since Zephyr follows zero warnings strategy I'd really prefer to clean up source code from the warnings rather than...

Note that in this case, this is a bogus warning.. disabling bogus warnings is not bad practice. It is just a way of keeping our sanity :)

But in any case this PR does not work :(.
That pointer is the output not the input, you want to save in ongoing_tx.radio_params.center_freq the valud that corresponds to freq_off

2021-12-23 15:00 UTC, alxelax commented
> Would a -Wno-address-of-packed-member for this component cmake fix the issue?

I'd say it will sweep warning under carpet. :) You are right unaligned access is a bit harmless for x86 architecture. However,
the build system is used for the whole source code including tested code and tests themselves. I'd prefer to follow up on all warnings within the tested components. They could be run on platforms where unaligned address access is fatal.
Moreover, changes in PR are not significant and do not impact both performance and functionality.

2021-12-23 15:03 UTC, alxelax commented
> > Since Zephyr follows zero warnings strategy I'd really prefer to clean up source code from the warnings rather than...
> 
> Note that in this case, this is a bogus warning.. disabling bogus warnings is not bad practice. It is just a way of keeping our sanity :)
> 
> But in any case this PR does not work :(. That pointer is the output not the input, you want to save in ongoing_tx.radio_params.center_freq the valud that corresponds to freq_off

Thnx. I'll fix it

2021-12-23 15:13 UTC, alxelax commented
> this is a bogus warning
For BabbleSim test core system - yes
For tested code - no

2021-12-23 15:17 UTC, aescolar commented
>For tested code - no

I'm only proposing disabling the warning in this library without affecting the overall Zephyr. (note that this module is not Zephyr specific, only the cmake file in this repo is made for Zephyr)

2022-01-03 12:49 UTC, alxelax commented
Zephyr's CI passed with these changes. I think it is better, faster, and more right to fix warnings even they are harmless rather than to create a special workaround for them in the BabbleSim build system. 
As you mentioned already it is mostly a sanity deal.

2022-01-03 15:10 UTC, aescolar approved these changes

2022-01-03 15:32 UTC, merged