Add more hal apis
BabbleSim/ext_NRF52_hw_models pull request #7
Opened 2020-06-15 10:33 UTC by auroraslb

Adds APIs for ppi, timer and rtc

2020-06-15 15:22 UTC, aescolar requested changes
Thanks @auroraslb . Just a few minor things

2020-06-15 15:22 UTC, aescolar commented on src/nrfx/hal/nrf_rtc.h
> +__STATIC_INLINE nrf_rtc_event_t nrf_rtc_compare_event_get(uint8_t index);
Now we have NRF_STATIC_INLINE, so please use it instead of redefining __STATIC_INLINE. (you may want to ensure you have fetched the latest master, and rebased your PR on top of it)

2020-06-15 15:22 UTC, aescolar commented on src/nrfx/hal/nrf_timer.c
> +      bs_trace_warning_line_time("Counter mode is not fully supported");
An extra \n at the of the message would be needed

2020-06-15 15:22 UTC, aescolar commented on src/nrfx/hal/nrf_timer.h
> +__STATIC_INLINE void nrf_timer_event_clear(NRF_TIMER_Type * p_reg, nrf_timer_event_t event);
Where you can take a line directly from the original file, please do so (so there is no differences on comparison) (In these prototypes, the difference is that you placed the 2nd parameter in the same line, while in the original files, they are in the next line)

2020-06-16 09:35 UTC, aescolar approved these changes
Thanks

2020-06-19 12:00 UTC, wopu-ot approved these changes

2020-06-19 12:17 UTC, merged